### ISSUE TITLE
Issues with the Ventura release

### ISSUE THREAD

**Issue by MichaelTrip** [Wamphyre/HP-ELITEDESK-800-G2-DM-MINI-HACKINTOSH-35W#2]
Hi,

i just bought myself a Elitedesk 800 G2 Mini and i tried to use your 1.5.1 version of the Ventura build. I have noticed 3 things so far:

- In the Kexts/USBPorts.kext/Contents/Info.plist there is a iMac17,1 reference. I changed that and my installation would boot further. But it didn't start the initial installation
- When disable Secure boot and Uefi the SecureBootModel needs to be on disabled instead of Default. Without that, my machine would automatically reboot

I have changed those two things above and it gets past the loading screen. After a while the screen stays blank without any output. 

I have tried playing a bit with the boot-args listed on https://github.com/acidanthera/WhateverGreen but that didn't work either. Can you help ?

**Comment by vhladiienko** [comment]
Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:

`OCB: StartImage failed - Aborted`

**Comment by hz2018tv** [comment]
I have ventura (v13.5.6??) installed by using a generic EFI for skylake. it runs fine without video acceleration and audio, then I tried to replace the generic EFI with this repo, it keeps rebooting, my device is elitedesk 800 g2 tower to an external monitor via vga (instead of dp)

**Comment by Wamphyre** [comment]
Hi! VGA port is not supported by modern macOS releases, you can only use HDMI or DP.
Anyway, what CPU/GPU you use in this G2 tower? Keep in mind that my EFI repo only support the G2 800 Mini model.

**Comment by Wamphyre** [comment]
> Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> 
> `OCB: StartImage failed - Aborted`

What macOS Ventura build are you using? I need to make some research and tests.

**Comment by lalaRLH** [comment]
> Hi,
> 
> i just bought myself a Elitedesk 800 G2 Mini and i tried to use your 1.5.1 version of the Ventura build. I have noticed 3 things so far:
> 
> * In the Kexts/USBPorts.kext/Contents/Info.plist there is a iMac17,1 reference. I changed that and my installation would boot further. But it didn't start the initial installation
> * When disable Secure boot and Uefi the SecureBootModel needs to be on disabled instead of Default. Without that, my machine would automatically reboot
> 
> I have changed those two things above and it gets past the loading screen. After a while the screen stays blank without any output.
> 
> I have tried playing a bit with the boot-args listed on https://github.com/acidanthera/WhateverGreen but that didn't work either. Can you help ?

There's a few things that come to mind:
1. How is the display connected, it is well known that cross-connectivity options will fail mid-way through booting the installer. IE connector is Mini Display one end and HDMI on the other. The drivers will fail approx 30% through the loading bar due to the mismatch. If you have mini display connected to the desktop, when the drivers kick in during OS installer boot, it will expect a mini display both ends, have anything else and you'll see a blank screen. There are exceptions and I cannot figure out the config specifics to get it going but generally when it works the VGA appears to work also (with hellish performance). Overall don't bother.

2. Your platform info is not populated accurately covering MLB, ROM, Serial Number and UUID. Extra validations are in place to ensure that users cannot spoof a working serial number on an iCloud locked device, as what used to happen is the serial of a non-locked device was entered, user completed the setup with the spoofed serial and logged into iCloud Services. This would actually then set the legitimate users devices to a state of being iCloud locked until they provided the Apple ID credentials of the person who had just taken over their serial. Without that detail their device would be iCloud locked. 

They would then need to convince apple they are the legal owner of the unit and go through a process to remove the device lock. Hence now, there needs to be a combination of MAC address within ROM, serial and UUID that aligns to the correct formula (as this hugely reduces ability to perform this attack). I believe it also runs a dynamic validation on bluetooth MAC.

This is also why it's so critical to never end up using the serial of a legitimate user as it can cause chaos and Apple do not respond well to it. For the system to boot, load the signed OS, and allow the device into iServices - this is required. 

Given you need to disable secure boot entirely, it suggests you are not meeting the criteria to boot due to a security check failing. Likely MLB/ROM/SerialNo/UUID being incorrectly populated. 

5. Intel VT-D enabled can cause this issue with DisableIOMapperMapping disabled (which it is here) as it may conflict with the firmware implementation and cause halting of the boot. This is the easiest one to check.

If you share an EFI file I can look at it more else it's a guessing game. I'd say 60% of the time the issue is a user going from mini-display to HDMI or attempting to use VGA.

**Comment by rykkardo8** [comment]
> Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> 
> `OCB: StartImage failed - Aborted`

I am also getting the error:
`OCB: StartImage failed - Aborted`

Were you able to figure it out?

**Comment by MichaelTrip** [comment]
> > Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> > 
> > `OCB: StartImage failed - Aborted`
> 
> I am also getting the error:
> `OCB: StartImage failed - Aborted`
> 
> Were you able to figure it out?

No sorry, I haven't. I also don't run Ventura anymore. I now only run Sanoma. Which works btw. Should I share my EFI?

**Comment by rykkardo8** [comment]
> No sorry, I haven't. I also don't run Ventura anymore. I now only run Sanoma. Which works btw. Should I share my EFI?
Thank you! I'd really appreciate that!

**Comment by rykkardo8** [comment]
> > > Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> > > `OCB: StartImage failed - Aborted`
> > 
> > 
> > I am also getting the error:
> > `OCB: StartImage failed - Aborted`
> > Were you able to figure it out?
> 
> No sorry, I haven't. I also don't run Ventura anymore. I now only run Sanoma. Which works btw. Should I share my EFI?

Thank you!  I'd really appreciate it if you could share your EFI with me

**Comment by MichaelTrip** [comment]
> > > > Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> > > > `OCB: StartImage failed - Aborted`
> > > 
> > > 
> > > I am also getting the error:
> > > `OCB: StartImage failed - Aborted`
> > > Were you able to figure it out?
> > 
> > 
> > No sorry, I haven't. I also don't run Ventura anymore. I now only run Sanoma. Which works btw. Should I share my EFI?
> 
> Thank you! I'd really appreciate it if you could share your EFI with me

Hi,

I just added my EFI dump here: https://github.com/MichaelTrip/HP-ELITEDESK-800-G2-DM-MINI-HACKINTOSH-35W-SANOMA

I have cleaned up the config.plist and removed my own SystemSerialNumber and SystemUUID. Generate those with GENSMBios for example: https://github.com/corpnewt/GenSMBIOS

**Comment by rykkardo8** [comment]
> > > > > Hi @MichaelTrip, did you manage to solve this? Version 2.0 for Ventura won't boot for me either, just gets stuck after selecting the boot option with below error:
> > > > > `OCB: StartImage failed - Aborted`
> > > > 
> > > > 
> > > > I am also getting the error:
> > > > `OCB: StartImage failed - Aborted`
> > > > Were you able to figure it out?
> > > 
> > > 
> > > No sorry, I haven't. I also don't run Ventura anymore. I now only run Sanoma. Which works btw. Should I share my EFI?
> > 
> > 
> > Thank you! I'd really appreciate it if you could share your EFI with me
> 
> Hi,
> 
> I just added my EFI dump here: https://github.com/MichaelTrip/HP-ELITEDESK-800-G2-DM-MINI-HACKINTOSH-35W-SANOMA
> 
> I have cleaned up the config.plist and removed my own SystemSerialNumber and SystemUUID. Generate those with GENSMBios for example: https://github.com/corpnewt/GenSMBIOS

Thank you so much! I installed it successfully :)
